import sys
from krita import *
from pathlib import Path
import xml.etree.ElementTree as ET
import re



application = Krita.instance()
currentDoc = application.activeDocument()
activeLayer = currentDoc.activeNode()
canvasWidth = currentDoc.width()
canvasHeight = currentDoc.height()

def fillCanvas():
    if not currentDoc:
        print("No active document!")
        return
    if not activeLayer or activeLayer.type() != "paintlayer":
        print("Select a paint layer first!")
        return
    activeLayer.scaleNode(QPoint(0,0), canvasWidth, canvasHeight, "Bicubic")
    layerBounds = currentDoc.activeNode()
    layerX = activeLayer.position().x()
    layerY = activeLayer.position().y()
    realBounds = layerBounds.bounds()
    absoluteX = realBounds.x()
    absoluteY = realBounds.y()
    movementX = (-1 * (absoluteX)) + (layerX)
    movementY = (-1 * (absoluteY)) + (layerY)
    activeLayer.move(movementX,movementY)
    currentDoc.activeNode()

def copyLayer():
    duplicatedLayer = activeLayer.duplicate()
    duplicatedLayer.setName(activeLayer.name() + " Copy")
    parentLayer = activeLayer.parentNode() or currentDoc.rootNode()
    parentLayer.addChildNode(duplicatedLayer, activeLayer)

    currentDoc.setActiveNode(duplicatedLayer)
    currentDoc.waitForDone()

def filterLayerOilpaint():
    oilpaintFilter = application.filter('oilpaint')
    oilpaintFilterConfig = oilpaintFilter.configuration()
    oilpaintFilterConfig.setProperty('brushsize', 5)
    oilpaintFilterConfig.setProperty('smooth', 30)
    oilpaintFilter.setConfiguration(oilpaintFilterConfig)
    oilpaintFilter.apply(activeLayer, 0, 0, currentDoc.width(), currentDoc.height())


# def parseXMLFilter():

#     xmlPath = currentDir / "imageedit.xml"
#     try:
#         tree = ET.parse(str(xmlPath))
#         root = tree.getroot()
#     except FileNotFoundError:
#         print(f"Error: Could not find the file at {xmlPath}")

#     for param in root.findall('.//param'):
        
#         prop_name = param.get('name')
        
#         prop_value = param.text 

#         clean_value = re.sub(r'\s+', ' ', prop_value).strip()


#         # if prop_name and clean_value:
#         #     print(f"halftoneFilterConfig.setProperty('{prop_name}', '{clean_value}')")


# def selectTop():
#     if currentDoc:
#         rootNodes = currentDoc.topLevelNodes()
        
#         if rootNodes:
#             topLayer = rootNodes[0]
#             currentDoc.setActiveNode(topLayer)
#         else:
#             print("No layers found in the document.")
#     else:
#         print("No active document found.")

        
#     currentDoc.refreshProjection()

def halftonePropertyBlock():
    CopiedLayer =(activeLayer.name() + " Copy")
    newNode = currentDoc.nodeByName(CopiedLayer)
    currentDoc.setActiveNode(newNode)
    halftoneFilter = application.filter('halftone')
    halftoneFilterConfig = halftoneFilter.configuration()
    halftoneFilterConfig.setProperty('RGBA_channel0_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator', 'screentone')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_equalization_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_frequency_x', '80')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_frequency_y', '80')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_rotation', '15')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_size_x', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_size_y', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_hardness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel0_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel1_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator', 'screentone')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_frequency_x', '80')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_frequency_y', '80')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_rotation', '45')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_size_x', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_size_y', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_hardness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel1_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel2_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator', 'screentone')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_frequency_x', '80')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_frequency_y', '80')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_resolution', '299')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_rotation', '75')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_size_x', '3.74')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_size_y', '3.74')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_hardness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel2_invert', 'false')
    halftoneFilterConfig.setProperty('alpha_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('alpha_background_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('alpha_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_generator', 'screentone')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_frequency_x', '30')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_frequency_y', '30')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_pattern', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_rotation', '45')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_size_x', '10')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_size_y', '10')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('alpha_hardness', '80')
    halftoneFilterConfig.setProperty('alpha_invert', 'false')
    halftoneFilterConfig.setProperty('color_model_id', 'RGBA')
    halftoneFilterConfig.setProperty('intensity_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('intensity_background_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('intensity_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_generator', 'screentone')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_frequency_x', '30')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_frequency_y', '30')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_rotation', '45')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_size_x', '10')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_size_y', '10')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('intensity_hardness', '80')
    halftoneFilterConfig.setProperty('intensity_invert', 'false')
    halftoneFilterConfig.setProperty('mode', 'independent_channels')
    halftoneFilter.setConfiguration(halftoneFilterConfig)
    halftoneFilter.apply(newNode, 0, 0, currentDoc.width(), currentDoc.height())



fillCanvas()
print(activeLayer.name())

copyLayer()
print(activeLayer.name())

filterLayerOilpaint()
print(activeLayer.name())

# selectTop()
# print(activeLayer.name())

halftonePropertyBlock()
print(activeLayer.name())

currentDoc.refreshProjection()