
print("Module loaded")  # to confirm import works
def test_func():
    print("hello")

def halftonePropertyBlock():
    halftoneFilter = application.filter('halftone')
    halftoneFilterConfig = halftoneFilter.configuration()

    halftoneFilterConfig.setProperty('RGBA_channel0_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator', 'screentone')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_equalization_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_frequency_x', '80')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_frequency_y', '80')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_rotation', '15')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_size_x', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_size_y', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel0_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('RGBA_channel0_hardness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel0_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel1_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator', 'screentone')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_frequency_x', '80')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_frequency_y', '80')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_rotation', '45')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_size_x', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_size_y', '3.75')
    halftoneFilterConfig.setProperty('RGBA_channel1_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('RGBA_channel1_hardness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel1_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel2_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator', 'screentone')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_frequency_x', '80')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_frequency_y', '80')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_resolution', '299')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_rotation', '75')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_size_x', '3.74')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_size_y', '3.74')
    halftoneFilterConfig.setProperty('RGBA_channel2_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('RGBA_channel2_hardness', '50')
    halftoneFilterConfig.setProperty('RGBA_channel2_invert', 'false')
    halftoneFilterConfig.setProperty('alpha_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('alpha_background_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('alpha_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_generator', 'screentone')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_frequency_x', '30')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_frequency_y', '30')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_pattern', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_rotation', '45')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_size_x', '10')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_size_y', '10')
    halftoneFilterConfig.setProperty('alpha_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('alpha_hardness', '80')
    halftoneFilterConfig.setProperty('alpha_invert', 'false')
    halftoneFilterConfig.setProperty('color_model_id', 'RGBA')
    halftoneFilterConfig.setProperty('intensity_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('intensity_background_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('intensity_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_generator', 'screentone')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_align_to_pixel_grid', 'true')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_align_to_pixel_grid_x', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_align_to_pixel_grid_y', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_background_color', '<!DOCTYPE color> <color> <RGB g="1" space="sRGB-elle-V2-srgbtrc.icc" b="1" r="1"/> </color>')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_background_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_brightness', '50')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_constrain_frequency', 'true')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_contrast', '50')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_equalization_mode', '2')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_foreground_color', '<!DOCTYPE color> <color> <RGB g="0" space="sRGB-elle-V2-srgbtrc.icc" b="0" r="0"/> </color>')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_foreground_opacity', '100')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_frequency_x', '30')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_frequency_y', '30')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_interpolation', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_invert', 'false')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_keep_size_square', 'true')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_pattern', '1')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_position_x', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_position_y', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_resolution', '300')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_rotation', '45')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_shape', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_shear_x', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_shear_y', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_size_mode', '0')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_size_x', '10')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_size_y', '10')
    halftoneFilterConfig.setProperty('intensity_generator_screentone_units', '0')
    halftoneFilterConfig.setProperty('intensity_hardness', '80')
    halftoneFilterConfig.setProperty('intensity_invert', 'false')
    halftoneFilterConfig.setProperty('mode', 'independent_channels')